### ISSUE TITLE
Dependency issue crashes my app in production

### ISSUE THREAD

**Issue by dbulic** [elixir-geolix/geolix#18]
I had to add ```{:mmdb2_decoder, "~> 0.1.0"},``` to mix.exs in v0.15, otherwise Geolix can't decode mmdb file.

**Comment by mneudert** [comment]
It looks like something went wrong with your update. When adding just Geolix to a new project the sub-dependency was properly resolved and everything worked fine.

Do you have by chance any version control in place to check if the dependency change was properly taken care of?

**Comment by dbulic** [comment]
Line in mix.lock says this:
```
  "geolix": {:hex, :geolix, "0.15.0", "daa7015007e52901d63034abdd08c7f2d4c55232d95118b2f425f7576da0eaf5", [:mix], [{:mmdb2_decoder, "~> 0.1.0", [hex: :mmdb2_decoder, repo: "hexpm", optional: false]}, {:poolboy, "~> 1.0", [hex: :poolboy, repo: "hexpm", optional: false]}], "hexpm"},
```
I have manually specified mmdb2_decoder as mentioned above. So, this looks good. I can try to get rid of mmdb2_decoder in mix.exs and redeploy to see if it will crash production. Will do that later, am busy with something at the moment.

**Comment by mneudert** [comment]
I think I found the actual source of your problems. It looks like I messed up the application configuration so your release (you are using releases, right?) did not build properly. Could you try the new version `0.15.1` to see if it works as expected?

**Comment by dbulic** [comment]
Yep, that fixed it. Good job.
